from __future__ import annotations

import json
from pathlib import Path

import polars as pl
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "data" / "fixtures" / "yield-observations.csv"
OUTPUT = ROOT / "docs" / "data" / "v1" / "yield-model.json"


def main() -> None:
    frame = pl.read_csv(INPUT)
    features = [
        "sun_hours",
        "water_balance_mm",
        "soil_organic_matter_pc",
        "days_in_ground",
        "disease_pressure",
    ]
    target = "yield_kg_per_sqm"
    train, test = train_test_split(frame.to_pandas(), test_size=0.25, random_state=7)
    model = LinearRegression()
    model.fit(train[features], train[target])
    predictions = model.predict(test[features])
    mae = mean_absolute_error(test[target], predictions)
    mean_target = max(float(test[target].mean()), 0.01)

    payload = {
        "schema_version": "1.0.0",
        "model_kind": "linear-regression",
        "features": features,
        "coefficients": dict(zip(features, [float(value) for value in model.coef_])),
        "intercept": float(model.intercept_),
        "mae_percent": round((mae / mean_target) * 100, 2),
        "training_rows": int(frame.height),
        "notes": "Generated by ml/train_yield_model.py with Polars and scikit-learn.",
    }
    OUTPUT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(OUTPUT), "mae_percent": payload["mae_percent"]}))


if __name__ == "__main__":
    main()
